export const CATEGORIES_LOADING = 'CATEGORIES_LOADING';
export const CATEGORIES_DONE = 'CATEGORIES_DONE';
export const ALL_POSTS_LOADING = 'ALL_POSTS_LOADING';
export const ALL_POSTS_DONE = 'ALL_POSTS_DONE';
export const M_CATEGORIES_ALL_POSTS_LOADING = 'M_CATEGORIES_ALL_POSTS_LOADING';

export const VOTE_LOADING = 'VOTE_LOADING';
export const VOTE_DONE = 'VOTE_DONE';