export const CATEGORIES_LOADING = 'CATEGORIES_LOADING';
export const CATEGORIES_DONE = 'CATEGORIES_DONE';
export const ALL_POSTS_LOADING = 'ALL_POSTS_LOADING';
export const ALL_POSTS_DONE = 'ALL_POSTS_DONE';
export const M_CATEGORIES_ALL_POSTS_LOADING = 'M_CATEGORIES_ALL_POSTS_LOADING';

export const VOTE_LOADING = 'VOTE_LOADING';
export const VOTE_DONE = 'VOTE_DONE';

export const POST_LOADING = 'POST_LOADING';
export const POST_DONE = 'POST_DONE';

export const COMMENTS_LOADING = 'COMMENTS_LOADING';
export const COMMENTS_DONE = 'COMMENTS_DONE';
export const COMMENT_VOTE_LOADING = 'COMMENT_VOTE_LOADING';
export const COMMENT_VOTE_DONE = 'COMMENT_VOTE_DONE';

export const POST_CREAT_LOADING = 'POST_CREAT_LOADING';
export const POST_CREATE_DONE = 'POST_CREATE_DONE';
export const POST_EDIT_LOADING = 'POST_EDIT_LOADING';
export const POST_EDIT_DONE = 'POST_EDIT_DONE';
export const POST_DELETE_LOADING = 'POST_DELETE_LOADING';
export const POST_DELETE_DONE = 'POST_DELETE_DONE';