export const VIEW_INDEX = 'VIEW_INDEX';
export const VIEW_CATEGORY = 'VIEW_CATEGORY';
export const VIEW_POST_DETAIL = 'VIEW_POST_DETAIL';
export const VIEW_POST_CREATE = 'VIEW_POST_CREATE';
export const VIEW_POST_EDIT = 'VIEW_POST_EDIT';

export const CATEGORIES_LOADING = 'CATEGORIES_LOADING';
export const CATEGORIES_DONE = 'CATEGORIES_DONE';
export const ALL_POSTS_LOADING = 'ALL_POSTS_LOADING';
export const ALL_POSTS_DONE = 'ALL_POSTS_DONE';
export const M_CATEGORIES_ALL_POSTS_LOADING = 'M_CATEGORIES_ALL_POSTS_LOADING';